Update requirements.txt
Fixing security alert + issue installing them:

ERROR: Cannot install -r requirements.txt (line 2) and asgiref==3.2.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested asgiref==3.2.5
    django 3.1.12 depends on asgiref<4 and >=3.2.10